[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 460800

lib_deps =
    lovyan03/LovyanGFX @ ^1.1.16
    tzapu/WiFiManager @ ^2.0.17
    bblanchon/ArduinoJson @ ^7.0.0

board_build.partitions = partitions.csv

build_flags =
    -DBOARD_CYD
    -DCORE_DEBUG_LEVEL=0
    -DWIDTH=240
    -DHEIGHT=320
